### PR TITLE
Fixes for eslint-loader and css-loader

### PR DESCRIPTION
**Pull request by artur79**

### CODE REVIEW

**Comment by simonmysun** [comment]
I think you forget to edit `webpack/webpack.prod.js`.

**Comment by HashemKhalifa** [comment]
@simonmysun fixed on production too you can build now normally, sorry for the inconvenient

**Comment by simonmysun** [comment]
I should thank you for the updates and thank you for this boilerplate!

**Comment by HashemKhalifa** [comment]
Thank you guys, that means a lot <3

**Pull request merged**
